### ISSUE TITLE
Steam workshop: ERROR! Download item XXXXXXX (Failure).

### ISSUE THREAD

**Issue by nuxy** [nuxy/docker-steamcmd-wine#2]
While I haven't been able to identify the exact release (Value forces an update when the CLI is executed manually), I do know that this issue did not occur in [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) version `1669935972` and earlier releases.

## Steam Workshop failures

It seems that there was changes in both Windows/Linux releases that **break workshop downloads** that are either initiated on the command-line or in-game using the `steam_ugc=<PublishedID>` configuration parameter.

### Example

The following will fail **regardless of whether using Steam account credentials or anonymous mode**.

```sh
$ steamcmd.exe + login anonymous +workshop_download_item 302200 278739322 +exit
```

This will result with the log entry:

```txt
> Steam/logs/workshop_log.txt

Loading workshop items for 0 installed apps for user [U:1:STEAMUSERID]:
[TIMESTAMP] [AppID 302200] Loaded workshop items in "Steam/steamapps/workshop" (0 installed, 1 needed)
[TIMESTAMP] [AppID 302200] Download item 278739322 requested by app
[TIMESTAMP] [AppID 302200] Starting Workshop download job (requested item 278739322)
[TIMESTAMP] [AppID 302200] Failed to get item info: Access Denied
[TIMESTAMP] [AppID 302200] Update canceled: Updating workshop item info failed (Missing configuration)
[TIMESTAMP] [AppID 302200] Download item 278739322 result : Failure
```

### Notes

- There currently is no known fix available (at the mercy of Valve development).
- If you do not import a [Steam Workshop](https://steamcommunity.com/workshop) the game should run without issue.

**Comment by Spafbi** [comment]
@nuxy - That workshop ID does not currently exist. Have you tried with other IDs?

https://steamcommunity.com/sharedfiles/filedetails/?id=278739322
![steam-error](https://github.com/nuxy/docker-steamcmd-wine/assets/11760047/89927061-d1cf-427f-9cd2-24a81b919b4a)

**Comment by nuxy** [comment]
@Spafbi I guess that test (one of many) included a truncated `<PublishID>`. The issue still occurs though with other IDs.  

Below is another example using the [SteamCMD Linux](https://github.com/nuxy/docker-steamcmd-wine/releases/tag/0.1.2) bundled release with a [valid Workshop ID](https://steamcommunity.com/sharedfiles/filedetails/?id=2787393227):

```
$ ./steamcmd +@sSteamCmdForcePlatformType windows +login anonymous +workshop_download_item 302200 2787393227 +quit

[TIMESTAMP] Loading workshop items for 2 installed apps for user [a:1:STEAMUSERID]:
[TIMESTAMP] [AppID 302200] Loaded workshop items in ".steam/steamapps/workshop" (0 installed, 0 needed)
[TIMESTAMP] [AppID 302200] Download item 2787393227 requested by app
[TIMESTAMP] [AppID 302200] Starting Workshop download job (requested item 2787393227)
[TIMESTAMP] [AppID 302200] Failed to get item info: Access Denied
[TIMESTAMP] [AppID 302200] Update canceled: Updating workshop item info failed (Missing configuration)
[TIMESTAMP] [AppID 302200] Download item 2787393227 result : Failure
```

Note:  I tried this in both a restricted user (`games`) and `root` user context. Unfortunately, the same result. :disappointed:

**Comment by nuxy** [comment]
One thing I failed to note..

In the case of the [Miscreated Dedicated Server](https://steamdb.info/app/302200), when the server initializes, the following errors occur in the `system.log`

```txt
<06:52:24> [STEAM] UGC content: 2787393227
<06:52:24> [Game Version]: RELEASE DEDICATED SERVER
<06:52:25> [STEAM] Download request made for content id: 2787393227
<06:52:25> [STEAM] Download failed for content id: 2787393227, code: 16
<06:52:25> [STEAM] This server will be forced to restart in 60 seconds.
```

Correct me if I'm wrong but I believe Steam **code 16** is a network timeout.

**Comment by Spafbi** [comment]
Sounds like a lot of things can trigger code 16, not just a network timeout. I was hoping to recreate your issue when just using steamcmd. However, I have tested multiple steam_ugc IDs and have been unable to replicate the issue when using steamcmd.exe on either Windows 11 or on Linux+WINE. This result is from my last test with Miscreated loading two steam_ugc IDs on Ubuntu 22.04+WINE 8.0.1+steamcmd version 1682708339:

```txt
<21:44:37> [STEAM] UGC content: 2075026891,2632671232
<21:44:37> [Game Version]: RELEASE DEDICATED SERVER
<21:44:38> [STEAM] Download request made for content id: 2075026891
<21:44:39> [STEAM] Download succeeded for content id: 2075026891
<21:44:39> [STEAM] Download request made for content id: 2632671232
<21:44:40> [STEAM] Download succeeded for content id: 2632671232
<21:44:40> [STEAM] Processing all UGC
<21:44:40> [STEAM] Processing UGC - contentId: 2075026891
<21:44:40> [STEAM] Installed UGC - contentId: 2075026891, size: 2298, path: Z:\mnt\120GB_SSD\miscreated\steamapps\workshop\content\299740\2075026891
<21:44:40> [STEAM] Processing UGC - contentId: 2632671232
<21:44:40> [STEAM] Installed UGC - contentId: 2632671232, size: 27594, path: Z:\mnt\120GB_SSD\miscreated\steamapps\workshop\content\299740\2632671232
<21:44:40> [STEAM] UGC CRC: 3991436201
```

**Comment by nuxy** [comment]
In the latter case, would you happen to be running in a Docker container? Based on the specs, I'm leaning towards OS native.

For me, the issue seems to be isolated to Docker, possibly related to changes in the Steam [VAC](https://help.steampowered.com/en/faqs/view/571A-97DA-70E9-FF74) system.

I will be looking into this throughout the week and will post what I find.

Thanks for your help.

**Comment by Spafbi** [comment]
I was not running in Docker for the latter test. If you like, I can test that later today to help validate.

**Comment by nuxy** [comment]
Follow-up...

Tested with a clean Ubuntu instance and several third-party Docker container dedicated server setups.  **In all cases, attempting to install workshops fail with the same "Access Denied" error.**  This seems to be an upstream issue that must be fixed by Valve (unless this was actually intended).

That said, I have posted this issue on Steam's _Help and Tips_ discussion board:
https://steamcommunity.com/discussions/forum/1/3833171151459228361

**Comment by Spafbi** [comment]
It still works for me in Docker, too:

```txt
[dedicated] loading hosting config hosting.cfg
steam_ugc 2075026891,2632671232
[STEAM] UGC content: 2075026891,2632671232
[Game Version]: RELEASE DEDICATED SERVER
[STEAM] Download request made for content id: 2075026891
[STEAM] Download succeeded for content id: 2075026891
[STEAM] Download request made for content id: 2632671232
[STEAM] Download succeeded for content id: 2632671232
[STEAM] Processing all UGC
[STEAM] Processing UGC - contentId: 2075026891
[STEAM] Installed UGC - contentId: 2075026891, size: 2298, path: Z:\opt\miscreated\steamapps\workshop\content\299740\2075026891
[STEAM] Processing UGC - contentId: 2632671232
[STEAM] Installed UGC - contentId: 2632671232, size: 27594, path: Z:\opt\miscreated\steamapps\workshop\content\299740\2632671232
[STEAM] UGC CRC: 3991436201
```

**Comment by Spafbi** [comment]
I even added the workshop ID you have in your log sample and it downloaded+installed w/o issue..

```txt
<18:08:02> [dedicated] loading hosting config hosting.cfg
<18:08:02> [STEAM] UGC content: 2075026891,2632671232,2787393227
<18:08:02> [Game Version]: RELEASE DEDICATED SERVER
<18:08:03> [STEAM] Download request made for content id: 2075026891
<18:08:03> [STEAM] Download succeeded for content id: 2075026891
<18:08:03> [STEAM] Download request made for content id: 2632671232
<18:08:04> [STEAM] Download succeeded for content id: 2632671232
<18:08:04> [STEAM] Download request made for content id: 2787393227
<18:08:05> [STEAM] Download succeeded for content id: 2787393227
<18:08:05> [STEAM] Processing all UGC
<18:08:05> [STEAM] Processing UGC - contentId: 2075026891
<18:08:05> [STEAM] Installed UGC - contentId: 2075026891, size: 2298, path: Z:\opt\miscreated\steamapps\workshop\content\299740\2075026891
<18:08:05> [STEAM] Processing UGC - contentId: 2632671232
<18:08:05> [STEAM] Installed UGC - contentId: 2632671232, size: 27594, path: Z:\opt\miscreated\steamapps\workshop\content\299740\2632671232
<18:08:05> [STEAM] Processing UGC - contentId: 2787393227
<18:08:05> [STEAM] Installed UGC - contentId: 2787393227, size: 76295, path: Z:\opt\miscreated\steamapps\workshop\content\299740\2787393227
<18:08:05> [STEAM] UGC CRC: 3162111076
```

This is on Ubuntu 22.04.2 LTS + WINE 8.0:
```bash
$ docker exec -it winetest wine --version
wine-8.0
```

And this version of steamcmd:
```bash
$ docker exec -it winetest /opt/steamcmd/steamcmd.sh --version +quit
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1682708339
-- type 'quit' to exit --
Loading Steam API...OK
```

**Comment by nuxy** [comment]
Here's a simple test using the apt distributed SteamCMD release (`1682708339`) and a clean installation of Ubuntu.

I tested this using my local environment and in an Amazon EC2 container. In both cases, same issue occurs. :frowning_face: 

```text
$ docker run -d --network host ubuntu:focal sleep infinity
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
4ae305ba1165        ubuntu:focal        "sleep infinity"    11 minutes ago      Up 11 minutes                           bold_heisenberg
$ docker exec -it 4ae305ba1165 /bin/bash
# apt update && apt install software-properties-common
# add-apt-repository multiverse
# dpkg --add-architecture i386
# apt update && apt install -y steam

... install info

# /usr/games/steamcmd +@sSteamCmdForcePlatformType windows +login anonymous +workshop_download_item 302200 2787393227 +quit
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1682708339
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 2787393227 ...
ERROR! Download item 2787393227 failed (Failure).root@host:/usr/games
```

Regarding your test. Are you running Steam as root in your set-up?

FYI, you should always run the Wine daemon in a restricted context.  In my case, while I run the daemon as the `games` user I have tested both scenarios (privileged/unprivileged) and still cannot get UGC content to work.

**Comment by Spafbi** [comment]
Yes, I'm running as a non-privileged user within the container:
```bash
steam          1       0  0 22:04 ?        00:00:00 start.exe /exec /opt/miscreated/Bin64_dedicated/MiscreatedServer.exe -sv_port 64090 -mis_gameserverid 100 +sv_maxplayers 36 +map islands
steam         74       1 99 22:05 ?        00:02:46 Z:\opt\miscreated\Bin64_dedicated\MiscreatedServer.exe -sv_port 64090 -mis_gameserverid 100 +sv_maxplayers 36 +map islands +http_startserver
```

After dinner I'll post my Dockerfiles and scripts I use to build my Ubuntu+WINE+steamcmd base container image as well as the Miscreated container image. I'll also post the script I used to launch the server.

**Comment by Spafbi** [comment]
For testing this issue, I started from scratch. This is a very straightforward build using an official Ubuntu 22.04 image, and then installing the latest versions of `steamcmd` and WINE, creating a `steam` user, and install the Miscreated server as the `steam` user.

Run the `build-server.sh` script to build the container image, After that you can create a `run` subdirectory in the same directory as the `run-server.sh` script, and place your desired `hosting.cfg` in that directory (`run/hosting.cfg`). Then execute the `run-server.sh` script to start the server. The server starts in the context of the `steam` user, and I've yet to have any failures loading steam_ugc IDs which currently exist.

Sample `hosting.cfg` for this test:
```ini
steam_ugc=2075026891,2632671232
sv_servername="My Test Server"
http_password=nopassword
```

[miscreated-server.zip](https://github.com/nuxy/docker-steamcmd-wine/files/11538064/miscreated-server.zip)

**Comment by nuxy** [comment]
Sorry for the delay on this.

I wanted to wait a bit to see if any recent `steamcmd` patches were released  before I committed to testing this again.

Note: At this point, I suspect this is a networking issue when running **Linux (as the Host OS)** while running `steamcmd` in a Docker container **(Debian variant as the Guest OS)**.  I have confirmed this behavior locally (Ubuntu Desktop) and using AWS EC2 instances (Linux 1/AL 2023 images).

The issue seems to only affect UGC download operations whether in game or CLI initiated.

[Spafbi](https://github.com/Spafbi) Are you running Docker under Windows?  I assume you are seeing `start.exe /exec` in the proc list output above.

If yes, could you please confirm the following works for you.  I suspect it will, which will confirm my suspicion.

```
$ docker run -d --network host ubuntu:focal sleep infinity
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
<CONTAINERID>        ubuntu:focal        "sleep infinity"    11 minutes ago      Up 11 minutes                           bold_heisenberg
$ docker exec -it <CONTAINERID> /bin/bash
# apt update && apt install software-properties-common
# add-apt-repository multiverse
# dpkg --add-architecture i386
# apt update && apt install -y steam

... install info

# /usr/games/steamcmd +@sSteamCmdForcePlatformType windows +login anonymous +workshop_download_item 302200 2787393227 +quit
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1682708339
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Downloading item 2787393227 ...
ERROR! Download item 2787393227 failed (Failure).root@host:/usr/games
```

Thanks for your help.

**Comment by Spafbi** [comment]
My Docker host is a bare-metal Ubuntu 22.04 LTS server. It worked for me, but I did use an Ubuntu Jammy Docker image and an altered set of commands.

That said, after seeing your last set of commands and rereading the initial issue post, I believe I figured out the core of your issue. In my prior examples where I reported success downloading the mod, I was not using the same command to download the workshop ID; I was instead using the game server's built-in `steam_ugc` cvar to download the mod. However, while you'll still need to use `steam_ugc` for the server to actually use the mod, if you want to pre-download the mod using steamcmd's `+workshop_download_item` option you need to use the app ID of the game client and not the game server's app ID. Here are the commands I used to fire up my Ubuntu Jammy Docker container and load everything.

```bash
$ docker run -d --network host ubuntu:jammy sleep infinity
$ docker ps
$ docker exec -it <CONTAINERID> /bin/bash
# apt update && apt install -y software-properties-common
# add-apt-repository multiverse -y
# apt install -y locales && locale-gen en_US.UTF-8 && update-locale  # Not strictly necessary, but added to get rid of setlocale warning
# dpkg --add-architecture i386
# apt update && echo "I AGREE" apt install -y steamcmd  # Installing steamcmd instead of steam
# /usr/games/steamcmd +@sSteamCmdForcePlatformType windows +login anonymous +app_update 302200 +workshop_download_item 299740 2787393227 +quit
```
Attached is the output log of the `steamcmd` command (from the above commands) to install the game server and pre-download the mod.
[steamcmd.txt](https://github.com/nuxy/docker-steamcmd-wine/files/12517640/steamcmd.txt)

**Comment by nuxy** [comment]
[Spafbi](https://github.com/Spafbi) -  I figured out what the issue was.

I was initially installing the game server as root, and then using a permission switch, which worked fine in prior releases.  Unfortunately, as result of an update in `steamcmd.exe` this no longer worked and quietly throws a segfault.

Due to this failure, in order to rule out the binary I attempted to reproduce the issue using an off-the-shelf container setup.

.. and then the following line threw me off course (which was cleared up by your post above) ..
```
$ steamcmd.exe + login anonymous +workshop_download_item 302200 278739322 +exit
```

During testing, the command I used above worked if the `app_update` install occurred beforehand, but that never happened resulting in the error and complete misdirection of the actual issue.  I was under the impression you could download Steam workshops without having the app installed as long it was public.  Apparently that is no longer the case.

Anyway, I have [pushed changes](https://github.com/nuxy/docker-steamcmd-wine/compare/1.0.1...1.1.0) that resolved the `steam_ugc` and CLI issues in this package.

Thanks for your help. Much appreciated.
